[package]
name = "go-rayyildiz-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
lambda_http = "0.8.1"
lambda_runtime = "0.8.1"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }


#[profile.release]
#strip = false
#opt-level = "s"
