name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: pip install ziglang

    - run: cargo install cargo-lambda
      continue-on-error: true

    - run: cargo check

    - run: cargo lambda build --release --arm64

    - uses: actions/upload-artifact@v3
      with:
        name: bootstrap
        path: target/lambda/go-rayyildiz-rs/
